### ISSUE TITLE
stack-2.7.3 fails to build with pantry-0.5.3

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/pantry#43]
In the next Stackage LTS 18 build:

```
/var/stackage/work/unpack-dir/unpacked/stack-2.7.3-cefa331420e8110d586c063358a61f55a5b9f5213075d98dce5e85411c2669b6/src/Stack/Setup.hs:847:24: error:
    • Couldn't match expected type ‘SimpleRepo’ with actual type ‘Repo’
    • In the first argument of ‘withRepo’, namely ‘repo’
      In the expression: withRepo repo
      In a stmt of a 'do' block:
        withRepo repo
          $ do mcwd <- traverse parseAbsDir =<< view workingDirL
               let cwd = fromMaybe (error "Invalid working directory") mcwd
               threads <- view $ configL . to configJobs
               let hadrianArgs = fmap T.unpack ...
                   hadrianScripts
                     | osIsWindows = hadrianScriptsWindows
                     | otherwise = hadrianScriptsPosix
               ....
    |
847 |        Pantry.withRepo repo $ do
    |                        ^^^^
```

Note I have not actually confirmed that this is due to API change in pantry-0.5.3 but it seems highly likely since this just broke now.

**Comment by juhp** [comment]
Yes I have restricted pantry  < 0.5.3 for lts-18.13.

**Comment by snoyberg** [comment]
I typically try to follow PVP version number assignment fairly closely, though I don't worry about the preemptive upper bounds.

**Comment by Bodigrim** [comment]
> I would recommend adding a corresponding Hackage revision to stack-2.7.3.

As a Hackage trustee I made a revision: https://hackage.haskell.org/package/stack-2.7.3/revisions/

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and it seems to have been addressed.
